In [3]:
class MyClass:
    x =5

In [5]:
p1 = MyClass()
print(p1.x) #instantiating the class

5


In [17]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age

p1 = Person('john',36)

print(p1.name)
print(p1.age)

john
36


In [19]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age

p1 = Person('john',36)
print(p1)

In [25]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def __str__(self):
        return f"{self.name}({self.age})"

p1 = Person('john',36)
print(p1)

john(36)


In [41]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def myfunc(self):
        print("my name is " + self.name)

p1 = Person("la la la la laaaaaaa",36)
p1.myfunc()

my name is la la la la laaaaaaa


In [47]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def myfunc(self):
        print("my name is " + self.name)

p1 = Person("John",36)
p1.age = 100
print(p1.age)

100


In [57]:
class Person:
    def __init__(self,fname,lname):
        self.firstname = fname
        self.lastname = lname
    def printname(self):
        print(self.firstname,self.lastname)

y = Person("john","Price")
y.printname()


class Student(Person):
    pass

john Price


In [59]:
#parent class it is the class that inherits from also known as base class 
#child class it inherits from another class / derived class 

x = Student("Mile","Nithu")
x.printname()

Mile Nithu


In [65]:
class Person:
    def __init__(self,fname,lname):
        self.firstname = fname
        self.lastname = lname
    def printname(self):
        print(self.firstname,self.lastname)

class Student(Person):
    def __init__(self,fname,lname):
        Person. __init__(self,fname,lname)

x = Student("Mike","Olsen")
x.printname()

Mike Olsen


In [75]:
class Student(Person):
    def __init__(self,fname,lname):
        super().__init__(fname,lname)
        self.graduationyear = 2019 #usinf super() function you do not need to use the name of parent class 
x = Student("Mike","olsen")
print(x.graduationyear)

2019


In [81]:
class Student(Person):
    def __init__(self,fname,lname):
        super().__init__(fname,lname)
        self.graduationyear = 2019
    def welcome(self):
        print("welcome",self.firstname,self.lastname,"to the class of",self.graduationyear)

x = Student("Mike",2024)
x.welcome()

welcome Mike 2024 to the class of 2019


In [93]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self._age = age

p = Person('Alice',25)
print(p._age)
p._age = 30
print(p._age)

25
30


In [1]:
import pandas as pd

In [7]:
a = pd.Series([1,2,3,4,5])
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [15]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s["a"]

1

In [19]:
data = {
    "calories":[450,500,380],
    "duration":[40,50,30]
}

In [23]:
df = pd.DataFrame(data)

In [25]:
print(df)

   calories  duration
0       450        40
1       500        50
2       380        30


In [27]:
print(df.loc[0])

calories    450
duration     40
Name: 0, dtype: int64


In [31]:
print(df.loc[[0,1]])

   calories  duration
0       450        40
1       500        50


In [33]:
print(df.loc[0,'duration'])

40


In [35]:
data = {
    "calories":[450,500,380],
    "duration":[40,50,30]
}
df = pd.DataFrame(data,index = ['day1','day2','day3'])


In [39]:
df = pd.read_csv('salaries.csv')

In [41]:
df

company                  job     degree  salary_more_then_100k  \
0       google      sales executive  bachelors                      0   
1       google      sales executive    masters                      0   
2       google     business manager  bachelors                      1   
3       google     business manager    masters                      1   
4       google  computer programmer  bachelors                      0   
5       google  computer programmer    masters                      1   
6   abc pharma      sales executive    masters                      0   
7   abc pharma  computer programmer  bachelors                      0   
8   abc pharma     business manager  bachelors                      0   
9   abc pharma     business manager    masters                      1   
10    facebook      sales executive  bachelors                      1   
11    facebook      sales executive    masters                      1   
12    facebook     business manager  bachelors                      1   
13    facebook     business manager    masters                      1   
14    facebook  computer programmer  bachelors                      1   
15    facebook  computer programmer    masters                      1   

    Unnamed: 4  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          NaN  
10         NaN  
11         NaN  
12         NaN  
13         NaN  
14         NaN  
15         NaN

In [43]:
print(df.to_string())

       company                  job     degree  salary_more_then_100k  Unnamed: 4
0       google      sales executive  bachelors                      0         NaN
1       google      sales executive    masters                      0         NaN
2       google     business manager  bachelors                      1         NaN
3       google     business manager    masters                      1         NaN
4       google  computer programmer  bachelors                      0         NaN
5       google  computer programmer    masters                      1         NaN
6   abc pharma      sales executive    masters                      0         NaN
7   abc pharma  computer programmer  bachelors                      0         NaN
8   abc pharma     business manager  bachelors                      0         NaN
9   abc pharma     business manager    masters                      1         NaN
10    facebook      sales executive  bachelors                      1         NaN
11    facebook  

In [45]:
df.shape

(16, 5)

In [49]:
print(df.head(3))

  company               job     degree  salary_more_then_100k  Unnamed: 4
0  google   sales executive  bachelors                      0         NaN
1  google   sales executive    masters                      0         NaN
2  google  business manager  bachelors                      1         NaN


In [51]:
print(df.tail(3))

     company                  job     degree  salary_more_then_100k  \
13  facebook     business manager    masters                      1   
14  facebook  computer programmer  bachelors                      1   
15  facebook  computer programmer    masters                      1   

    Unnamed: 4  
13         NaN  
14         NaN  
15         NaN  


In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   company                16 non-null     object 
 1   job                    16 non-null     object 
 2   degree                 16 non-null     object 
 3   salary_more_then_100k  16 non-null     int64  
 4   Unnamed: 4             0 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 772.0+ bytes


In [61]:
#Numpy
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [73]:
arr = np.array('ba ba baaaa ba ba banana ba ba ba ba banananaaaa ooooo')
print(arr)

ba ba baaaa ba ba banana ba ba ba ba banananaaaa ooooo


In [75]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [83]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row:',arr[1,4])

5th element on 2nd row: 10


In [89]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [97]:
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [11]:
class employee:
    def __init__(self,name):
        self.name = name
s1 = employee("sonali")
print(s1.name)


sonali


In [37]:
#private or like attributes and methods
class account:
    def __init__(self,acc_no,acc_pass):
        self.acc_no = acc_no
        self.__acc_pass = acc_pass #"__" double underscore is used to determine private attribute
    def reset_paswd(self):
        print(self.__acc_pass)
 
acc1 = account("1234","xyz")
print(acc1.reset_paswd())

xyz
None


In [43]:
#private method 
class person:
    def __hello(self):
        print("Hello!")
    def wlcm(self):
        self.__hello()
        
p1 = person()
print(p1.wlcm())

Hello!
None


In [ ]:
#inheritence
# single inheritence


In [51]:
#Prent class 

class vehicle:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    def show_details(self):
        print("I am a vehicle")
        print("mileage of a vehicle",self.mileage)
        print("cost of vehicle:",self.cost)

v1 = vehicle(50,50000)
v1.show_details()

I am a vehicle
mileage of a vehicle 50
cost of vehicle: 50000


In [57]:
class car(vehicle):
    def show_car(self):
        print("I am a car")

c1 = car(40,4000)
c1.show_details()

I am a vehicle
mileage of a vehicle 40
cost of vehicle: 4000


In [81]:
#Multiple inheritance

#parent class one 

class Parent1:
    def assign_string1(self,str1):
        self.str1 = str1
    def show_str1(self):
        return self.str1

In [89]:
class Parent2:
    def assign_string2(self,str2):
        self.str2 = str2
    def show_str2(self):
        return self.str2

In [91]:
#child class 

class Derived(Parent1,Parent2):
    def assign_string3(self,str3):
        self.str3 = str3
    def show_str3(self):
        return self.str3

d1 = Derived()
d1.assign_string1('one')
d1.assign_string2('two')
d1.assign_string3('three')

In [95]:
d1.show_str1()

'one'

In [97]:
d1.show_str2()

'two'

In [99]:
d1.show_str3()

'three'

In [101]:
#Multi level inheritence
class Parent():
    def assign_name(self,name):
        self.name = name
    def show_name(self):
        return self.name

In [125]:
class Child(Parent):
    def assign_age(self,age):
        self.age = age
    def show_age(self):
        return self.age

In [127]:
class Grandchild(Child):
    def assign_gender(self,gender):
        self.gender = gender
    def show_gender(self):
        return self.gender

In [129]:
gc = Grandchild()
gc.assign_name("nithu")
gc.assign_age("22")
gc.assign_gender("F")

In [131]:
gc.show_name()

'nithu'

In [133]:
gc.show_age()

'22'

In [137]:
gc.show_gender()

'F'

In [1]:
#Polymorphism

In [16]:
class math:
    def add(self,a:int,b:int):
        return a+b
    def add(self,a: float,b: float):
        return a+b

In [18]:
math = math()
print(math.add(5,3))
print(math.add(5.0,3.2))

8
8.2


In [ ]:
#Types of Polymorphism
#1.Overloading : Multiple methods with the same name but different parameter

In [20]:
#overloading with different number of parameters

class Area:
    def find_area(self,a=None,b=None):
        if a!=None and b!=None:
            print("Area of rectangle:",a*b)
        elif a!=None:
            print("Area of Rectangle:",a*a)
        else:
            print("Nothing to find")

obj1 = Area()
obj1.find_area()
obj1.find_area(10)
obj1.find_area(10,20)

Nothing to find
Area of Rectangle: 100
Area of rectangle: 200


In [24]:
#overloading method to handle different data types 

class Calculator:
    def add(self,a=None,b=None):
        if isinstance(a,str) and isinstance(b,str):
            print('Concatenation of string',a + b)
        elif isinstance(a,int) and isinstance(b,int):
            print('Sum of intergers',a+b)
        else:
            print('Invalid datatype or missng arguments')

calc = Calculator()
calc.add(10,20)
calc.add("Hello","world")
calc.add(10)

Sum of intergers 30
Concatenation of string Helloworld
Invalid datatype or missng arguments


In [34]:
#Overloading a method for different shapes (circle,square and rectangle)

import math

class Shape:
    def area(self,radius=None,side=None,length=None,breadth=None):
        if radius is not None:
            print(f"Area of circle{math.pi*radius**2}")
        elif side is not None:
            print(f"Area of square{side**2}")
        elif length is not None and breadth is not None:
            print(f"Area of rectangle:{length*breadth}")
        else:
            print("Please provide valid dimensions")

shape = Shape()
shape.area(radius=7)
shape.area(side=4)
shape.area(length=10,breadth=5)
shape.area()

Area of circle153.93804002589985
Area of square16
Area of rectangle:50
Please provide valid dimensions


In [36]:
#Method Overriding : When a derived class provides a specific implementation of a method that is already defined in its base class

In [44]:
#Basic example

class Animal:
    def sound(self):
        return "some sound"
class dog(Animal):
    def sound(self):
        return "Bark"
class Cat(Animal):
    def sound(self):
        return "meow"

dog = dog()
Cat = Cat()

print(dog.sound())
print(Cat.sound())

Bark
meow


In [48]:
#Method Overriding with additional functionalities 

class Vehicle:
    def start(self):
        return "Vehicle is starting"
class Car(Vehicle):
    def start(self):
        base_mesage = super().start()  #calling the superclass method
        return f"{base_mesage} with a roar"
class Motorcycle(Vehicle):
    def start(self):
        return "Motorcycle is running"

car = Car()
motorcycle = Motorcycle()

print(car.start())
print(motorcycle.start())


Vehicle is starting with a roar
Motorcycle is running


In [52]:
class Vehicle:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    def show_details(self):
        print("I am a vehicle")
        print("mileage of vehicle",self.mileage)
        print("cost of vehicle",self.cost)

class Car(Vehicle):
    def __init__(self,mileage,cost,tyres,hp):
        super().__init__(mileage,cost)
        self.tyres = tyres
        self.hp = hp
    def show_details(self):
        super().show_details()
        print("I am a car")
        print("No. of tyres of vehicle",self.tyres)
        print("Horse power is:",self.hp)

my_car = Car(15,50000,4,120)
my_car.show_details()

I am a vehicle
mileage of vehicle 15
cost of vehicle 50000
I am a car
No. of tyres of vehicle 4
Horse power is: 120


In [75]:
#encapsulation

class BankAccount:
    def __init__(self,balance):
        self.__balance = balance
    def deposit(self,amount):
        if amount > 0:
            self.__balance += amount
        else:
            print("Deposit amount should be positive")
    def withdraw(self,amount):
        if 0<amount<self.__balance:
            self.__balance -= amount
        else:
            print("Insufficient funds or invalid amount")
    def get_balance(self):
        return self.__balance # Accessing encapsulated data through a method
account = BankAccount(10000)
print("Current balance",account.get_balance())

account.deposit(500)
print("New balance",account.get_balance())

account.withdraw(1000)
print("New balance",account.get_balance())

Current balance 10000
New balance 10500
New balance 9500


In [1]:
pip show numpy

Name: numpy
Version: 1.26.4
Summary: Fundamental package for array computing in Python
Home-page: https://numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: Copyright (c) 2005-2023, NumPy Developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above
       copyright notice, this list of conditions and the following
       disclaimer in the documentation and/or other materials provided
       with the distribution.

    * Neither the name of the NumPy Developers nor the names of any
       contributors may be used to endorse or promote products derived
       from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYR

In [3]:
pip freeze

aext-assistant @ file:///C:/b/abs_7e0qjcige6/croot/aext-assistant_1717062202219/work
aext-assistant-server @ file:///C:/b/abs_261y2c9vsm/croot/aext-assistant-server_1717060019302/work
aext-core @ file:///C:/b/abs_1e882xlg8y/croot/aext-core_1717056431204/work
aext-core-server @ file:///C:/b/abs_24av6ljtvu/croot/aext-core-server_1717075079138/work
aext-panels @ file:///C:/b/abs_44bc4hv663/croot/aext-panels_1717062218055/work
aext-panels-server @ file:///C:/b/abs_7f9_48fhp3/croot/aext-panels-server_1717060738001/work
aext-share-notebook @ file:///C:/b/abs_4bhc14ko2x/croot/aext-share-notebook_1717059348177/work
aext-share-notebook-server @ file:///C:/b/abs_2b3c16a8t0/croot/aext-share-notebook-server_1717057990383/work
aext-shared @ file:///C:/b/abs_1ex0tj8g9m/croot/aext-shared_1716991146845/work
aiobotocore @ file:///C:/b/abs_a0zxrsvpwx/croot/aiobotocore_1714464454692/work
aiohttp @ file:///C:/b/abs_8860tt1424/croot/aiohttp_1715108828392/work
aioitertools @ file:///tmp/build/80754af9/aioit

In [39]:
#create a package


In [57]:
a = 'ahsitin'
new = ''
for i in range(len(a)-1,-1,-1):
    new = new + a[i]
    
  

In [59]:
print(new)

nitisha


In [12]:
a = 'nithu'
new = ''
if a == new:
    print(a)
else:
    print('Not a palindrome')

Not a palindrome


In [14]:
vowels = ['a','e','i','o','u']
count_vowels = 0
a = 'chaitanya'
for i in a:
    if i in vowels:
        count_vowels = count_vowels +1

print(count_vowels)

4


In [16]:
a = 4
for i in range(a-1,0,-1):
    a=a*i
    
print(a)  

24


In [18]:
class Myfirstpackage:
    def alphabets(self,arangement):
        new = ''
        for i in range(len(arangement)-1,-1,-1):
            new = new + arangement[i]
        return new

    def palindrome(self,name):
        new = ''
        for i in range(len(name)-1,-1,-1):
            new = new + name[i]
        if name == new:
            return name
        else:
            return 'Not a palindrome'

    def vowels(self,count):
        vowels = ['a','e','i','o','u']
        count_vowels = 0
        for i in count:
            if i in vowels:
                count_vowels = count_vowels +1
        return count_vowels

abc = Myfirstpackage()
print(abc.alphabets('nithu'))
print(abc.palindrome('mom'))
print(abc.vowels('nitisha'))
    

uhtin
mom
3


In [20]:
#array
#list array and numpy array

In [22]:
import numpy as np
arr=np.array ([10,20,30,40,50])

arr_mul = arr * 5
print(arr_mul)

[ 50 100 150 200 250]


In [24]:
array_1d = np.arange(12)
print(array_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
array_2d = array_1d.reshape(3,4)
print(array_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
try:
    array_incomatible = array_1d.reshape(2,6)
except ValueError as e:
    print("\nError:",e)

array_valid = array_1d.reshape(6,2)
print("Valid reshape (4x3):\n",array_valid)



Valid reshape (4x3):
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [48]:
a = ['apple','banana','kiwi','guava','pinapple']
a.extend(['apricot','blueberry'])
print(a)

['apple', 'banana', 'kiwi', 'guava', 'pinapple', 'apricot', 'blueberry']


In [54]:
a1 = np.array([1,2,3])
a2 = np.array([1,2.0,3.3],
              [4,5,6.7])
a3 = np.array([[1,2,3],
              [4,5,6],
               [7,8,9]]
              [[10,11,12],
              [13,14,15],
              [16,17,18]])

<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?


TypeError: Field elements must be 2- or 3-tuples, got '4'

In [60]:
zeros = np.zeroes(3,2,4)

AttributeError: module 'numpy' has no attribute 'zeroes'